version: '3'

services:
    test:
      build: .
      command: "poetry run pytest -m 'not long'"

    test-long:
      build: .
      command: "poetry run pytest"

    lint:
      build: .
      command: "poetry run flake8 ."
